"""Generated by packages/contracts/generate_contracts.py. Do not edit."""

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypedDict

ConstraintSource = Literal['explicit_user', 'inferred_model', 'catalog', 'system']

ConstraintStrength = Literal['hard', 'soft']

ConstraintStatus = Literal['active', 'superseded', 'conflicted']

RunStatus = Literal['queued', 'running', 'completed', 'failed', 'cancelled']

RunEventType = Literal['run_created', 'run_started', 'task', 'artifact', 'model_execution', 'policy_gate', 'result', 'run_failed', 'run_cancelled']

WireProductCategory = Literal['phone', 'headphones', 'charger', 'cable', 'case']

WireRetrievalChannel = Literal['search', 'recommendation', 'ads']

class RequirementConstraint(TypedDict):
    constraintId: str
    field: str
    value: Any
    source: ConstraintSource
    strength: ConstraintStrength
    confidence: float
    turnId: str
    status: ConstraintStatus

class IdentitySession(TypedDict):
    identityId: str
    sessionId: str
    issuedAt: str
    expiresAt: str

class AgentRun(TypedDict):
    runId: str
    identityId: str
    sessionId: str
    status: RunStatus
    message: str
    confirmed: bool
    idempotencyKey: NotRequired[str | None]
    result: NotRequired[Any]
    errorCode: NotRequired[str | None]
    createdAt: str
    updatedAt: str
    cancelRequested: bool

class AgentRunEvent(TypedDict):
    eventId: str
    runId: str
    taskId: NotRequired[str | None]
    parentTaskId: NotRequired[str | None]
    sequence: int
    eventType: RunEventType
    timestamp: str
    schemaVersion: Literal['2.0']
    payload: dict[str, Any]

class CreateRunRequest(TypedDict):
    message: str
    confirmed: NotRequired[bool]

class CreateRunResponse(TypedDict):
    runId: str
    status: RunStatus
    eventsUrl: str
    runUrl: str

class DiscoveryWireRequest(TypedDict):
    query: str
    requested_categories: list[WireProductCategory]
    use_cases: list[str]
    preferred_brands: list[str]
    primary_product_ids: list[str]
    max_price: NotRequired[float | None]
    limit: int
    sponsored_allowed: bool
    identity_id: NotRequired[str]
    session_id: NotRequired[str]
    personalization_enabled: bool
    recent_product_ids: NotRequired[list[str]]
    excluded_product_ids: NotRequired[list[str]]
    ad_exposure_product_ids: NotRequired[list[str]]

class CandidateWireRecord(TypedDict):
    spu_id: str
    product_id: str
    sku_id: str
    offer_id: str
    title: str
    category: WireProductCategory
    brand: str
    price: float
    currency: Literal['CNY']
    stock: int
    channel: WireRetrievalChannel
    channel_score: float
    normalized_score: float
    reasons: list[str]
    sponsored: bool

class FusionWireRequest(TypedDict):
    channels: list[dict[str, Any]]
    limit: int

class BundleOptimizationWireRequest(TypedDict):
    items: list[CandidateWireRecord]
    requested_categories: list[WireProductCategory]
    intent: Literal['precise', 'catalog', 'exploratory', 'bundle', 'compare']
    budget_max: NotRequired[float | None]
    top_n: int
