#!/usr/bin/env python3
"""Generate dependency-free TypeScript and Python contract types from JSON Schema."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = Path(__file__).with_name("commerce-agent-v2.schema.json")
TS_PATH = ROOT / "agent-control-plane" / "src" / "generated" / "contracts-v2.ts"
PY_PATH = ROOT / "src" / "shoprec" / "generated_contracts_v2.py"


def ref_name(value: str) -> str:
    return value.rsplit("/", 1)[-1]


def type_values(schema: dict[str, Any]) -> list[str]:
    value = schema.get("type")
    if isinstance(value, str):
        return [value]
    if isinstance(value, list) and all(isinstance(item, str) for item in value):
        return value
    return []


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return ref_name(schema["$ref"])
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(item, ensure_ascii=False) for item in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts_type(item) for item in schema["anyOf"])
    values = type_values(schema)
    mapped: list[str] = []
    for value in values:
        if value == "string":
            mapped.append("string")
        elif value in {"number", "integer"}:
            mapped.append("number")
        elif value == "boolean":
            mapped.append("boolean")
        elif value == "null":
            mapped.append("null")
        elif value == "array":
            mapped.append(f"Array<{ts_type(schema.get('items', {}))}>")
        elif value == "object":
            mapped.append("Record<string, unknown>")
        else:
            mapped.append("unknown")
    return " | ".join(mapped) if mapped else "unknown"


def py_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return ref_name(schema["$ref"])
    if "const" in schema:
        return f"Literal[{schema['const']!r}]"
    if "enum" in schema:
        return "Literal[" + ", ".join(repr(item) for item in schema["enum"]) + "]"
    if "anyOf" in schema:
        return " | ".join(py_type(item) for item in schema["anyOf"])
    values = type_values(schema)
    mapped: list[str] = []
    for value in values:
        if value == "string":
            mapped.append("str")
        elif value == "number":
            mapped.append("float")
        elif value == "integer":
            mapped.append("int")
        elif value == "boolean":
            mapped.append("bool")
        elif value == "null":
            mapped.append("None")
        elif value == "array":
            mapped.append(f"list[{py_type(schema.get('items', {}))}]")
        elif value == "object":
            mapped.append("dict[str, Any]")
        else:
            mapped.append("Any")
    return " | ".join(mapped) if mapped else "Any"


def generate_ts(definitions: dict[str, dict[str, Any]]) -> str:
    lines = ["// Generated by packages/contracts/generate_contracts.py. Do not edit.", ""]
    for name, schema in definitions.items():
        if schema.get("type") == "object" and "properties" in schema:
            lines.append(f"export interface {name} {{")
            required = set(schema.get("required", []))
            for field, field_schema in schema["properties"].items():
                optional = "" if field in required else "?"
                lines.append(f"  {field}{optional}: {ts_type(field_schema)};")
            lines.extend(["}", ""])
        else:
            lines.extend([f"export type {name} = {ts_type(schema)};", ""])
    return "\n".join(lines).rstrip() + "\n"


def generate_py(definitions: dict[str, dict[str, Any]]) -> str:
    lines = [
        '"""Generated by packages/contracts/generate_contracts.py. Do not edit."""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any, Literal, NotRequired, TypedDict",
        "",
    ]
    aliases: list[tuple[str, dict[str, Any]]] = []
    objects: list[tuple[str, dict[str, Any]]] = []
    for name, schema in definitions.items():
        (objects if schema.get("type") == "object" and "properties" in schema else aliases).append((name, schema))
    for name, schema in aliases:
        lines.extend([f"{name} = {py_type(schema)}", ""])
    for name, schema in objects:
        lines.append(f"class {name}(TypedDict):")
        required = set(schema.get("required", []))
        for field, field_schema in schema["properties"].items():
            value = py_type(field_schema)
            lines.append(f"    {field}: {value}" if field in required else f"    {field}: NotRequired[{value}]")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_or_check(path: Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if check:
        return current == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    definitions = schema["$defs"]
    outputs = [(TS_PATH, generate_ts(definitions)), (PY_PATH, generate_py(definitions))]
    failures = [str(path) for path, content in outputs if not write_or_check(path, content, args.check)]
    if failures:
        print("Generated contracts are stale: " + ", ".join(failures))
        return 1
    for path, _ in outputs:
        print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
