import type { CatalogProduct } from "./contracts.js";

const VERSION = "normal-3c-snapshot-v1";
const QUOTE_VERSION = "quote-snapshot-2026-08-01";
const QUOTE_VALID_UNTIL = "2099-01-01T00:00:00Z";

type CatalogSeed = Omit<
  CatalogProduct,
  "spuId" | "offerId" | "currency" | "quoteVersion" | "quoteValidUntil" | "dataSource"
>;

const DEMO_CATALOG_SEEDS: CatalogSeed[] = [
  {
    productId: "phone-iphone-15",
    skuId: "sku-iphone-15-128-blue",
    title: "Apple iPhone 15 128GB 蓝色",
    category: "phone",
    brand: "Apple",
    price: 5299,
    stock: 32,
    tags: ["手机", "拍照", "续航", "轻便", "usb-c"],
    ecosystem: "ios",
    connectors: ["usb-c", "bluetooth"],
    protocols: ["usb-pd", "bluetooth-aac"],
    maxPowerWatts: 27,
    sponsored: false,
    catalogVersion: VERSION,
  },
  {
    productId: "phone-xiaomi-14",
    skuId: "sku-xiaomi-14-256-black",
    title: "Xiaomi 14 256GB 黑色",
    category: "phone",
    brand: "Xiaomi",
    price: 3999,
    stock: 25,
    tags: ["手机", "拍照", "游戏", "续航", "快充"],
    ecosystem: "android",
    connectors: ["usb-c", "bluetooth"],
    protocols: ["usb-pd", "pps", "xiaomi-fast-charge", "bluetooth-aac"],
    maxPowerWatts: 90,
    sponsored: true,
    adBid: 2.1,
    adQuality: 0.92,
    catalogVersion: VERSION,
  },
  {
    productId: "phone-honor-200",
    skuId: "sku-honor-200-256-green",
    title: "HONOR 200 256GB 绿色",
    category: "phone",
    brand: "HONOR",
    price: 2799,
    stock: 18,
    tags: ["手机", "人像", "拍照", "续航", "快充"],
    ecosystem: "android",
    connectors: ["usb-c", "bluetooth"],
    protocols: ["usb-pd", "pps", "bluetooth-aac"],
    maxPowerWatts: 66,
    sponsored: false,
    catalogVersion: VERSION,
  },
  {
    productId: "headphones-airpods-pro-2",
    skuId: "sku-airpods-pro-2-usbc",
    title: "Apple AirPods Pro 2 USB-C",
    category: "headphones",
    brand: "Apple",
    price: 1599,
    stock: 41,
    tags: ["耳机", "通勤", "降噪", "音质", "ios"],
    ecosystem: "ios",
    connectors: ["usb-c", "bluetooth"],
    protocols: ["bluetooth-aac"],
    sponsored: false,
    catalogVersion: VERSION,
  },
  {
    productId: "headphones-soundcore-liberty",
    skuId: "sku-soundcore-liberty-black",
    title: "Soundcore Liberty 降噪真无线耳机",
    category: "headphones",
    brand: "Soundcore",
    price: 499,
    stock: 76,
    tags: ["耳机", "通勤", "降噪", "音质", "性价比"],
    ecosystem: "universal",
    connectors: ["usb-c", "bluetooth"],
    protocols: ["bluetooth-aac", "bluetooth-ldac"],
    sponsored: false,
    catalogVersion: VERSION,
  },
  {
    productId: "headphones-xiaomi-buds",
    skuId: "sku-xiaomi-buds-white",
    title: "Xiaomi Buds Pro 真无线耳机",
    category: "headphones",
    brand: "Xiaomi",
    price: 699,
    stock: 54,
    tags: ["耳机", "通勤", "降噪", "android"],
    ecosystem: "android",
    connectors: ["usb-c", "bluetooth"],
    protocols: ["bluetooth-aac", "bluetooth-ldac"],
    sponsored: true,
    adBid: 1.4,
    adQuality: 0.86,
    catalogVersion: VERSION,
  },
  {
    productId: "charger-apple-20w",
    skuId: "sku-apple-charger-20w",
    title: "Apple 20W USB-C 电源适配器",
    category: "charger",
    brand: "Apple",
    price: 129,
    stock: 90,
    tags: ["充电器", "usb-c", "快充", "便携"],
    ecosystem: "universal",
    connectors: ["usb-c"],
    protocols: ["usb-pd"],
    maxPowerWatts: 20,
    sponsored: false,
    catalogVersion: VERSION,
  },
  {
    productId: "charger-ugreen-65w",
    skuId: "sku-ugreen-gan-65w",
    title: "UGREEN 65W GaN USB-C 充电器",
    category: "charger",
    brand: "UGREEN",
    price: 199,
    stock: 63,
    tags: ["充电器", "usb-c", "快充", "多口", "便携"],
    ecosystem: "universal",
    connectors: ["usb-c"],
    protocols: ["usb-pd", "pps"],
    maxPowerWatts: 65,
    sponsored: true,
    adBid: 1.7,
    adQuality: 0.9,
    catalogVersion: VERSION,
  },
  {
    productId: "charger-xiaomi-90w",
    skuId: "sku-xiaomi-charger-90w",
    title: "Xiaomi 90W USB-C 快充套装",
    category: "charger",
    brand: "Xiaomi",
    price: 299,
    stock: 38,
    tags: ["充电器", "usb-c", "快充", "90w"],
    ecosystem: "android",
    connectors: ["usb-c"],
    protocols: ["usb-pd", "pps", "xiaomi-fast-charge"],
    maxPowerWatts: 90,
    sponsored: false,
    catalogVersion: VERSION,
  },
  {
    productId: "charger-irrelevant-camera",
    skuId: "sku-camera-charger-sponsored",
    title: "相机专用电池充电器",
    category: "charger",
    brand: "Other",
    price: 99,
    stock: 99,
    tags: ["相机", "专用电池"],
    ecosystem: "universal",
    connectors: ["proprietary"],
    protocols: ["camera-battery"],
    maxPowerWatts: 10,
    sponsored: true,
    adBid: 9.9,
    adQuality: 0.2,
    catalogVersion: VERSION,
  },
];

export const DEMO_CATALOG: CatalogProduct[] = DEMO_CATALOG_SEEDS.map((product) => ({
  ...product,
  spuId: `spu-${product.productId}`,
  offerId: `offer-${product.skuId}-self`,
  currency: "CNY",
  quoteVersion: QUOTE_VERSION,
  quoteValidUntil: QUOTE_VALID_UNTIL,
  dataSource: {
    source: "local_snapshot",
    sourceVersion: VERSION,
    providerId: "normal-3c-v1",
  },
}));
